dependencies {
    implementation project(':turip-app')
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    implementation 'org.json:json:20231013'

    testImplementation project(':turip-app').sourceSets.test.output
    testImplementation "org.springframework.boot:spring-boot-testcontainers"
    testImplementation "org.testcontainers:testcontainers-junit-jupiter:2.0.2"
    testImplementation "org.testcontainers:testcontainers:2.0.2"
    testImplementation "org.testcontainers:testcontainers-mysql:2.0.2"
}
