spring:
  profiles:
    active: local

  # ===================================================================
  # =                            공통 설정                             =
  # ===================================================================
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: false # Flyway 비활성화
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never

region:
  category:
    domestic:
      etc:
        image-url: ${DOMESTIC_ETC_IMAGE_URL}
    overseas:
      etc:
        image-url: ${OVERSEAS_ETC_IMAGE_URL}

jwt:
  secret-key: ${JWT_SECRET_KEY}
  refresh-token-expiration-ms: 2592000000  # 30일

kakao:
  api:
    key: ${KAKAO_API_KEY}
    url: https://dapi.kakao.com/v2/local/search/keyword.json

google:
  client-id: ${GOOGLE_CLIENT_ID}
  api:
    key: ${GOOGLE_API_KEY}
    url: https://maps.googleapis.com/maps/api/place/textsearch/json

youtube:
  api:
    key: ${YOUTUBE_API_KEY}
    url: https://www.googleapis.com/youtube/v3/videos

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    health:
      show-details: never

server:
  tomcat:
    mbeanregistry:
      enabled: true

logging:
  level:
    root: INFO
