spring:
  datasource:
    url: jdbc:mysql://localhost:3306/turip_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: false # Flyway 비활성화
