spring:
  config:
    activate:
      on-profile: loadtest
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: turip
    password: turip_pw
  jpa:
    properties:
      hibernate:
        validator:
          apply_to_ddl: false
  management:
    endpoint:
      health:
        show-details: always

jwt:
  access-token-expiration-ms: 86400000  # 1일

cookie:
  secure: false  # HTTP 환경에서 쿠키 전송 허용
