services:
  nginx:
    image: nginx:latest
    container_name: turip-nginx
    restart: always
    ports:
      - "${NGINX_PORT:-80}:80"
      - "8081:8081"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - turip-network

  blue:
    image: teamturip/turip-backend:${APP_IMAGE_TAG:-latest}
    container_name: blue
    restart: always
    expose:
      - "8080"
    env_file:
      - .env
    networks:
      - turip-network
    volumes:
      - /home/ubuntu/logs/app:/logs

  green:
    image: teamturip/turip-backend:${APP_IMAGE_TAG:-latest}
    container_name: green
    restart: always
    expose:
      - "8080"
    env_file:
      - .env
    networks:
      - turip-network
    volumes:
      - /home/ubuntu/logs/app:/logs

  admin:
    image: teamturip/turip-backend:${ADMIN_IMAGE_TAG:-latest}
    container_name: turip-admin
    restart: always
    expose:
      - "8081"
    environment:
      <<: *app_env
      SERVER_PORT: 8081
      OTEL_SERVICE_NAME: turip-admin
    networks:
      - turip-network
    volumes:
      - /home/ubuntu/logs/admin:/logs

networks:
  turip-network:
    external: true
