package turip.account.domain;

import static java.util.Arrays.stream;

import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import java.util.Random;

public enum NicknameWord {
    FIRST_TRAVELING("여행하는", Category.FIRST),
    FIRST_CODING("코딩하는", Category.FIRST),
    FIRST_RUNNING("달리는", Category.FIRST),
    FIRST_WALKING("걷는", Category.FIRST),
    FIRST_SLEEPING("잠자는", Category.FIRST),
    FIRST_DANCING("춤추는", Category.FIRST),
    FIRST_SINGING("노래하는", Category.FIRST),
    FIRST_COOKING("요리하는", Category.FIRST),
    FIRST_STUDYING("공부하는", Category.FIRST),
    FIRST_EXPLORING("탐험하는", Category.FIRST),
    FIRST_CAMPING("캠핑하는", Category.FIRST),
    FIRST_SURFING("서핑하는", Category.FIRST),
    FIRST_SWIMMING("수영하는", Category.FIRST),
    FIRST_FLYING("비행하는", Category.FIRST),
    FIRST_TAKING_PHOTOS("사진찍는", Category.FIRST),
    FIRST_DRAWING("그림그리는", Category.FIRST),
    FIRST_WRITING("글쓰는", Category.FIRST),
    FIRST_PRESENTING("발표하는", Category.FIRST),
    FIRST_MEETING("회의하는", Category.FIRST),
    FIRST_PLANNING("계획하는", Category.FIRST),
    FIRST_ORGANIZING("정리하는", Category.FIRST),
    FIRST_CLEANING("청소하는", Category.FIRST),
    FIRST_REPAIRING("수리하는", Category.FIRST),
    FIRST_ASSEMBLING("조립하는", Category.FIRST),
    FIRST_DISMANTLING("정비하는", Category.FIRST),
    FIRST_EXPERIMENTING("실험하는", Category.FIRST),
    FIRST_ANALYZING("분석하는", Category.FIRST),
    FIRST_TESTING("테스트하는", Category.FIRST),
    FIRST_DEBUGGING("디버깅하는", Category.FIRST),
    FIRST_DEPLOYING("배포하는", Category.FIRST),
    FIRST_DESIGNING("설계하는", Category.FIRST),
    FIRST_STRATEGIZING("기획하는", Category.FIRST),
    FIRST_IMAGINING("상상하는", Category.FIRST),
    FIRST_PONDERING("고민하는", Category.FIRST),
    FIRST_CHOOSING("선택하는", Category.FIRST),
    FIRST_CHALLENGING("도전하는", Category.FIRST),
    FIRST_GIVING_UP("쉬어가는", Category.FIRST),
    FIRST_RETRYING("다시시도하는", Category.FIRST),
    FIRST_PRACTICING("연습하는", Category.FIRST),
    FIRST_TRAINING("훈련하는", Category.FIRST),
    FIRST_MEDITATING("명상하는", Category.FIRST),
    FIRST_RESTING("휴식하는", Category.FIRST),
    FIRST_ZONING_OUT("여유부리는", Category.FIRST),
    FIRST_STROLLING("산책하는", Category.FIRST),
    FIRST_HIKING("등산하는", Category.FIRST),
    FIRST_FISHING("낚시하는", Category.FIRST),
    FIRST_DOING_YOGA("요가하는", Category.FIRST),
    FIRST_STRETCHING("스트레칭하는", Category.FIRST),
    FIRST_HEATING("달구는", Category.FIRST),
    FIRST_COOLING("식히는", Category.FIRST),
    FIRST_WAITING("기다리는", Category.FIRST),
    FIRST_DISCOVERING("발견하는", Category.FIRST),
    FIRST_RECORDING("기록하는", Category.FIRST),
    FIRST_SAVING("저장하는", Category.FIRST),
    FIRST_DELETING("비우는", Category.FIRST),
    FIRST_UPLOADING("업로드하는", Category.FIRST),
    FIRST_DOWNLOADING("다운로드하는", Category.FIRST),
    FIRST_SHARING("공유하는", Category.FIRST),
    FIRST_CONNECTING("연결하는", Category.FIRST),
    FIRST_SEPARATING("분리하는", Category.FIRST),
    FIRST_STACKING("쌓는", Category.FIRST),
    FIRST_TOPPLING("바로잡는", Category.FIRST),
    FIRST_MAKING("만드는", Category.FIRST),
    FIRST_FIXING("고치는", Category.FIRST),
    FIRST_BREAKING("손보는", Category.FIRST),
    FIRST_HIDING("숨는", Category.FIRST),
    FIRST_SEEKING("찾는", Category.FIRST),
    FIRST_GUARDING("지키는", Category.FIRST),
    FIRST_ATTACKING("해결하는", Category.FIRST),
    FIRST_DEFENDING("방어하는", Category.FIRST),
    FIRST_ESCAPING("벗어나는", Category.FIRST),
    FIRST_TRACKING("추적하는", Category.FIRST),
    FIRST_OBSERVING("관찰하는", Category.FIRST),
    FIRST_QUESTIONING("질문하는", Category.FIRST),
    FIRST_EXPLAINING("설명하는", Category.FIRST),
    FIRST_PERSUADING("설득하는", Category.FIRST),
    FIRST_DESIGNING_IN_PROGRESS("설계중인", Category.FIRST),
    FIRST_MAKING_MISTAKES("배워가는", Category.FIRST),
    FIRST_SUCCEEDED("성공한", Category.FIRST),
    FIRST_FAILED("성장한", Category.FIRST),
    FIRST_PREPARING("준비하는", Category.FIRST),
    FIRST_BOOKING("예약하는", Category.FIRST),
    FIRST_CHECKING("확인하는", Category.FIRST),
    FIRST_INSPECTING("점검하는", Category.FIRST),
    FIRST_COORDINATING("조율하는", Category.FIRST),
    FIRST_COLLABORATING("협업하는", Category.FIRST),
    FIRST_COACHING("코칭하는", Category.FIRST),
    FIRST_TEACHING("가르치는", Category.FIRST),
    FIRST_LEARNING("배우는", Category.FIRST),
    FIRST_CHEERING("응원하는", Category.FIRST),
    FIRST_CELEBRATING("축하하는", Category.FIRST),
    FIRST_APPRECIATING("감사하는", Category.FIRST),
    FIRST_PRAISING("칭찬하는", Category.FIRST),
    FIRST_HELPING("도와주는", Category.FIRST),
    FIRST_PROMISING("약속하는", Category.FIRST),
    FIRST_NEGOTIATING("협상하는", Category.FIRST),
    FIRST_COLLECTING("수집하는", Category.FIRST),
    FIRST_CONQUERING("정복하는", Category.FIRST),
    FIRST_SEARCHING("탐색하는", Category.FIRST),
    FIRST_REVIEWING("복습하는", Category.FIRST),

    SECOND_CUTE("귀여운", Category.SECOND),
    SECOND_HAPPY("행복한", Category.SECOND),
    SECOND_EXCITED("신난", Category.SECOND),
    SECOND_SLEEPY("졸린", Category.SECOND),
    SECOND_CALM("차분한", Category.SECOND),
    SECOND_SERIOUS("진지한", Category.SECOND),
    SECOND_QUIRKY("엉뚱한", Category.SECOND),
    SECOND_SMART("똑똑한", Category.SECOND),
    SECOND_RELAXED("느긋한", Category.SECOND),
    SECOND_BUSY("바쁜", Category.SECOND),
    SECOND_LEISURELY("여유로운", Category.SECOND),
    SECOND_FREE("자유로운", Category.SECOND),
    SECOND_FLUTTERING("설레는", Category.SECOND),
    SECOND_SHY("수줍은", Category.SECOND),
    SECOND_BRAVE("용감한", Category.SECOND),
    SECOND_TIMID("겁많은", Category.SECOND),
    SECOND_CONFIDENT("당당한", Category.SECOND),
    SECOND_SHY_HEARTED("소심한", Category.SECOND),
    SECOND_CURIOUS("호기심많은", Category.SECOND),
    SECOND_STOIC("무뚝뚝한", Category.SECOND),
    SECOND_KIND("친절한", Category.SECOND),
    SECOND_CRANKY("담백한", Category.SECOND),
    SECOND_SENSITIVE("섬세한", Category.SECOND),
    SECOND_INDIFFERENT("무던한", Category.SECOND),
    SECOND_PASSIONATE("열정적인", Category.SECOND),
    SECOND_COLD_HEARTED("이성적인", Category.SECOND),
    SECOND_WARM("따뜻한", Category.SECOND),
    SECOND_COLD("시원한", Category.SECOND),
    SECOND_REALISTIC("현실적인", Category.SECOND),
    SECOND_IDEALISTIC("이상적인", Category.SECOND),
    SECOND_OPTIMISTIC("낙관적인", Category.SECOND),
    SECOND_PESSIMISTIC("균형적인", Category.SECOND),
    SECOND_IMPULSIVE("충동적인", Category.SECOND),
    SECOND_PLANNED("계획적인", Category.SECOND),
    SECOND_SPONTANEOUS("즉흥적인", Category.SECOND),
    SECOND_CAUTIOUS("신중한", Category.SECOND),
    SECOND_STUBBORN("의지있는", Category.SECOND),
    SECOND_FLEXIBLE("유연한", Category.SECOND),
    SECOND_HONEST("솔직한", Category.SECOND),
    SECOND_SECRETIVE("조심스러운", Category.SECOND),
    SECOND_ACTIVE("활발한", Category.SECOND),
    SECOND_QUIET("조용한", Category.SECOND),
    SECOND_COMPOSED("침착한", Category.SECOND),
    SECOND_OVEREXCITED("흥분한", Category.SECOND),
    SECOND_PEACEFUL("평화로운", Category.SECOND),
    SECOND_ANXIOUS("포근한", Category.SECOND),
    SECOND_STABLE("안정된", Category.SECOND),
    SECOND_CONFUSED("정리된", Category.SECOND),
    SECOND_FOCUSED("집중한", Category.SECOND),
    SECOND_DISTRACTED("명랑한", Category.SECOND),
    SECOND_PERFECTIONIST("완벽주의적인", Category.SECOND),
    SECOND_CARELESS("소탈한", Category.SECOND),
    SECOND_METICULOUS("꼼꼼한", Category.SECOND),
    SECOND_BOLD("대담한", Category.SECOND),
    SECOND_HUMBLE("겸손한", Category.SECOND),
    SECOND_ARROGANT("자신있는", Category.SECOND),
    SECOND_CREATIVE("창의적인", Category.SECOND),
    SECOND_IMITATIVE("모방하는", Category.SECOND),
    SECOND_EXPERIMENTAL("실험적인", Category.SECOND),
    SECOND_CONSERVATIVE("보수적인", Category.SECOND),
    SECOND_LOGICAL("논리적인", Category.SECOND),
    SECOND_EMOTIONAL("감성적인", Category.SECOND),
    SECOND_INTUITIVE("직관적인", Category.SECOND),
    SECOND_CALCULATING("현명한", Category.SECOND),
    SECOND_INNOCENT("순수한", Category.SECOND),
    SECOND_CYNICAL("성숙한", Category.SECOND),
    SECOND_POSITIVE("긍정적인", Category.SECOND),
    SECOND_NEGATIVE("희망적인", Category.SECOND),
    SECOND_BRIGHT("밝은", Category.SECOND),
    SECOND_DARK("은은한", Category.SECOND),
    SECOND_FUNNY("유머있는", Category.SECOND),
    SECOND_BECAME_SERIOUS("진지해진", Category.SECOND),
    SECOND_TIRED("편안한", Category.SECOND),
    SECOND_REFRESHED("상쾌한", Category.SECOND),
    SECOND_LETHARGIC("여유있는", Category.SECOND),
    SECOND_MOTIVATED("의욕적인", Category.SECOND),
    SECOND_RESTLESS("차근한", Category.SECOND),
    SECOND_SLOW("느린", Category.SECOND),
    SECOND_FAST("빠른", Category.SECOND),
    SECOND_STABLE_NATURED("안정적인", Category.SECOND),
    SECOND_UNSTABLE("균형잡힌", Category.SECOND),
    SECOND_PLEASANT("유쾌한", Category.SECOND),
    SECOND_NEUTRAL("담담한", Category.SECOND),
    SECOND_SCARY("든든한", Category.SECOND),
    SECOND_METICULOUS_PLANNED("용의주도한", Category.SECOND),
    SECOND_RECKLESS("과감한", Category.SECOND),
    SECOND_RESPONSIBLE("책임감있는", Category.SECOND),
    SECOND_OFF_GUARD("긴장푼", Category.SECOND),
    SECOND_AWAKE("깨어있는", Category.SECOND),
    SECOND_DAZED("맑은", Category.SECOND),
    SECOND_GENTLE("상냥한", Category.SECOND),
    SECOND_SOCIABLE("사교적인", Category.SECOND),
    SECOND_INTROVERTED("내성적인", Category.SECOND),
    SECOND_VIBRANT("활기찬", Category.SECOND),
    SECOND_GLOOMY("잔잔한", Category.SECOND),
    SECOND_MILD("온화한", Category.SECOND),
    SECOND_TENSE("산뜻한", Category.SECOND),
    SECOND_INDIFFERENTLY("부드러운", Category.SECOND),
    SECOND_CONFIDENT_SELF("자신감있는", Category.SECOND),
    SECOND_EXPECTANT("기대하는", Category.SECOND),

    THIRD_GORILLA("고릴라", Category.THIRD),
    THIRD_MONKEY("원숭이", Category.THIRD),
    THIRD_CAT("고양이", Category.THIRD),
    THIRD_DOG("강아지", Category.THIRD),
    THIRD_FOX("여우", Category.THIRD),
    THIRD_BEAR("곰", Category.THIRD),
    THIRD_RABBIT("토끼", Category.THIRD),
    THIRD_LION("사자", Category.THIRD),
    THIRD_TIGER("호랑이", Category.THIRD),
    THIRD_WOLF("늑대", Category.THIRD),
    THIRD_PANDA("판다", Category.THIRD),
    THIRD_PENGUIN("펭귄", Category.THIRD),
    THIRD_OTTER("수달", Category.THIRD),
    THIRD_HAMSTER("햄스터", Category.THIRD),
    THIRD_KOALA("코알라", Category.THIRD),
    THIRD_RACCOON("너구리", Category.THIRD),
    THIRD_CAPYBARA("카피바라", Category.THIRD),
    THIRD_PARROT("앵무새", Category.THIRD),
    THIRD_OCTOPUS("문어", Category.THIRD),
    THIRD_WHALE("고래", Category.THIRD),
    THIRD_SHARK("상어", Category.THIRD),
    THIRD_DOLPHIN("돌고래", Category.THIRD),
    THIRD_EAGLE("독수리", Category.THIRD),
    THIRD_SPARROW("참새", Category.THIRD),
    THIRD_OWL("부엉이", Category.THIRD),
    THIRD_EAGLE_OWL("올빼미", Category.THIRD),
    THIRD_TURTLE("거북이", Category.THIRD),
    THIRD_LIZARD("도마뱀", Category.THIRD),
    THIRD_DINOSAUR("공룡", Category.THIRD),
    THIRD_DRAGON("용", Category.THIRD),
    THIRD_UNICORN("유니콘", Category.THIRD),
    THIRD_ROBOT("로봇", Category.THIRD),
    THIRD_ANDROID("안드로이드", Category.THIRD),
    THIRD_CYBORG("사이보그", Category.THIRD),
    THIRD_ALIEN("외계인", Category.THIRD),
    THIRD_ASTRONAUT("우주인", Category.THIRD),
    THIRD_KNIGHT("기사", Category.THIRD),
    THIRD_WIZARD("마법사", Category.THIRD),
    THIRD_PIRATE("해적", Category.THIRD),
    THIRD_NINJA("닌자", Category.THIRD),
    THIRD_SAMURAI("사무라이", Category.THIRD),
    THIRD_EXPLORER("탐험가", Category.THIRD),
    THIRD_SCIENTIST("과학자", Category.THIRD),
    THIRD_DEVELOPER("개발자", Category.THIRD),
    THIRD_DESIGNER("디자이너", Category.THIRD),
    THIRD_PLANNER("기획자", Category.THIRD),
    THIRD_PAINTER("화가", Category.THIRD),
    THIRD_MUSICIAN("음악가", Category.THIRD),
    THIRD_WRITER("작가", Category.THIRD),
    THIRD_POET("시인", Category.THIRD),
    THIRD_STUDENT("학생", Category.THIRD),
    THIRD_TEACHER("선생님", Category.THIRD),
    THIRD_PROFESSOR("교수", Category.THIRD),
    THIRD_RESEARCHER("연구원", Category.THIRD),
    THIRD_CHEF("요리사", Category.THIRD),
    THIRD_BAKER("제빵사", Category.THIRD),
    THIRD_FARMER("농부", Category.THIRD),
    THIRD_FISHER("어부", Category.THIRD),
    THIRD_MERCHANT("상인", Category.THIRD),
    THIRD_TRAVELER("여행자", Category.THIRD),
    THIRD_WANDERER("방랑자", Category.THIRD),
    THIRD_ADVENTURER("모험가", Category.THIRD),
    THIRD_OBSERVER("관찰자", Category.THIRD),
    THIRD_RECORDER("기록자", Category.THIRD),
    THIRD_GUARDIAN("수호자", Category.THIRD),
    THIRD_ADMINISTRATOR("관리자", Category.THIRD),
    THIRD_ARCHITECT("설계자", Category.THIRD),
    THIRD_CREATOR("창조자", Category.THIRD),
    THIRD_DESTROYER("개척자", Category.THIRD),
    THIRD_COLLECTOR("수집가", Category.THIRD),
    THIRD_SCOUT("정찰병", Category.THIRD),
    THIRD_STRATEGIST("전략가", Category.THIRD),
    THIRD_ANALYST("분석가", Category.THIRD),
    THIRD_HACKER("해커", Category.THIRD),
    THIRD_MAKER("메이커", Category.THIRD),
    THIRD_ARTISAN("장인", Category.THIRD),
    THIRD_BEGINNER("초보자", Category.THIRD),
    THIRD_EXPERT("고수", Category.THIRD),
    THIRD_MASTER("마스터", Category.THIRD),
    THIRD_ROOKIE("루키", Category.THIRD),
    THIRD_HERO("영웅", Category.THIRD),
    THIRD_HELPER("조력자", Category.THIRD),
    THIRD_VILLAIN("반전주인공", Category.THIRD),
    THIRD_RIVAL("라이벌", Category.THIRD),
    THIRD_PARTNER("파트너", Category.THIRD),
    THIRD_FRIEND("친구", Category.THIRD),
    THIRD_COLLEAGUE("동료", Category.THIRD),
    THIRD_LEADER("리더", Category.THIRD),
    THIRD_FOLLOWER("팔로워", Category.THIRD),
    THIRD_AUDIENCE("관객", Category.THIRD),
    THIRD_DEER("사슴", Category.THIRD),
    THIRD_HORSE("말", Category.THIRD),
    THIRD_SHEEP("양", Category.THIRD),
    THIRD_GOAT("염소", Category.THIRD),
    THIRD_FROG("개구리", Category.THIRD),
    THIRD_CROW("까마귀", Category.THIRD),
    THIRD_HEDGEHOG("고슴도치", Category.THIRD),
    THIRD_SEAL("물개", Category.THIRD),
    THIRD_SEA_LION("바다사자", Category.THIRD),
    THIRD_CRANE("두루미", Category.THIRD);

    public enum Category {
        FIRST,
        SECOND,
        THIRD
    }

    private static final Map<Category, List<NicknameWord>> WORDS_BY_CATEGORY = buildByCategory();

    private final String text;
    private final Category category;

    NicknameWord(String text, Category category) {
        this.text = text;
        this.category = category;
    }

    public String text() {
        return text;
    }

    public Category category() {
        return category;
    }

    public static String createRandomNickname(Random random) {
        NicknameWord first = random(Category.FIRST, random);
        NicknameWord second = random(Category.SECOND, random);
        NicknameWord third = random(Category.THIRD, random);
        return first.text + " " + second.text + " " + third.text;
    }

    private static Map<Category, List<NicknameWord>> buildByCategory() {
        Map<Category, List<NicknameWord>> map = new EnumMap<>(Category.class);
        for (Category category : Category.values()) {
            map.put(category, List.copyOf(stream(values())
                    .filter(word -> word.category == category)
                    .toList())
            );
        }
        return Map.copyOf(map);
    }

    private static NicknameWord random(Category category, Random random) {
        List<NicknameWord> words = WORDS_BY_CATEGORY.get(category);
        return words.get(random.nextInt(words.size()));
    }
}
