package turip.place.domain;

import java.util.Arrays;
import lombok.Getter;

@Getter
public enum GoogleMapCategory {
    // 자동차
    CAR_DEALER("🚗 자동차 판매점", "car_dealer"),
    CAR_RENTAL("🚗 렌터카", "car_rental"),
    CAR_REPAIR("🚗 자동차 정비소", "car_repair"),
    CAR_WASH("🚗 세차장", "car_wash"),
    ELECTRIC_VEHICLE_CHARGING_STATION("🚗 전기차 충전소", "electric_vehicle_charging_station"),
    GAS_STATION("⛽ 주유소", "gas_station"),
    PARKING("🅿️ 주차장", "parking"),
    REST_STOP("🚗 휴게소", "rest_stop"),

    // 비즈니스
    CORPORATE_OFFICE("🏢 기업 사무실", "corporate_office"),
    FARM("🌾 농장", "farm"),
    RANCH("🐄 목장", "ranch"),

    // 문화
    ART_GALLERY("🖼️ 미술관", "art_gallery"),
    ART_STUDIO("🖼️ 화실", "art_studio"),
    AUDITORIUM("🎭 공연장", "auditorium"),
    CULTURAL_LANDMARK("🏛️ 문화적 명소", "cultural_landmark"),
    HISTORICAL_PLACE("🏛️ 사적지", "historical_place"),
    MONUMENT("🏛️ 기념물", "monument"),
    MUSEUM("🏛️ 박물관", "museum"),
    PERFORMING_ARTS_THEATER("🎭 공연 예술 극장", "performing_arts_theater"),
    SCULPTURE("🖼️ 조각상", "sculpture"),

    // 교육
    LIBRARY("📚 도서관", "library"),
    PRESCHOOL("🏫 유치원", "preschool"),
    PRIMARY_SCHOOL("🏫 초등학교", "primary_school"),
    SECONDARY_SCHOOL("🏫 중·고등학교", "secondary_school"),
    UNIVERSITY("🎓 대학교", "university"),

    // 엔터테인먼트 및 여가
    ADVENTURE_SPORTS_CENTER("🎢 체험형 스포츠 센터", "adventure_sports_center"),
    AMPHITHEATRE("🎭 원형극장", "amphitheatre"),
    AMUSEMENT_CENTER("🎡 오락 센터", "amusement_center"),
    AMUSEMENT_PARK("🎡 놀이공원", "amusement_park"),
    AQUARIUM("🏞️ 수족관", "aquarium"),
    BANQUET_HALL("🎤 연회장", "banquet_hall"),
    BARBECUE_AREA("🍽️ 바비큐장", "barbecue_area"),
    BOTANICAL_GARDEN("🏞️ 식물원", "botanical_garden"),
    BOWLING_ALLEY("🎳 볼링장", "bowling_alley"),
    CASINO("🎰 카지노", "casino"),
    CHILDRENS_CAMP("🏕️ 어린이 캠프", "childrens_camp"),
    COMEDY_CLUB("🎤 코미디 클럽", "comedy_club"),
    COMMUNITY_CENTER("🏢 커뮤니티 센터", "community_center"),
    CONCERT_HALL("🎤 콘서트 홀", "concert_hall"),
    CONVENTION_CENTER("🏢 컨벤션 센터", "convention_center"),
    CULTURAL_CENTER("🏛️ 문화 센터", "cultural_center"),
    CYCLING_PARK("🚴 자전거 공원", "cycling_park"),
    DANCE_HALL("💃 댄스 홀", "dance_hall"),
    DOG_PARK("🐶 애견 공원", "dog_park"),
    EVENT_VENUE("🎤 이벤트 장소", "event_venue"),
    FERRIS_WHEEL("🎡 관람차", "ferris_wheel"),
    GARDEN("🏞️ 정원", "garden"),
    HIKING_AREA("🥾 등산로", "hiking_area"),
    HISTORICAL_LANDMARK("🏛️ 역사적 명소", "historical_landmark"),
    INTERNET_CAFE("☕ 인터넷 카페", "internet_cafe"),
    KARAOKE("🎤 노래방", "karaoke"),
    MARINA("⛵ 마리나", "marina"),
    MOVIE_RENTAL("🎬 영화 대여점", "movie_rental"),
    MOVIE_THEATER("🎬 영화관", "movie_theater"),
    NATIONAL_PARK("🏞️ 국립공원", "national_park"),
    NIGHT_CLUB("🎤 나이트클럽", "night_club"),
    OBSERVATION_DECK("🔭 전망대", "observation_deck"),
    OFF_ROADING_AREA("🏞️ 오프로드 구역", "off_roading_area"),
    OPERA_HOUSE("🎭 오페라 하우스", "opera_house"),
    PARK("🏞️ 공원", "park"),
    PHILHARMONIC_HALL("🎼 필하모닉 홀", "philharmonic_hall"),
    PICNIC_GROUND("🥪 피크닉장", "picnic_ground"),
    PLANETARIUM("🔭 천문관", "planetarium"),
    PLAZA("🏞️ 광장", "plaza"),
    ROLLER_COASTER("🎢 롤러코스터", "roller_coaster"),
    SKATEBOARD_PARK("🛹 스케이트보드 공원", "skateboard_park"),
    STATE_PARK("🏞️ 주립공원", "state_park"),
    TOURIST_ATTRACTION("📍 관광 명소", "tourist_attraction"),
    VIDEO_ARCADE("🕹️ 비디오 아케이드", "video_arcade"),
    VISITOR_CENTER("📍 방문자 센터", "visitor_center"),
    WATER_PARK("🏊‍♂️ 워터파크", "water_park"),
    WEDDING_VENUE("💒 결혼식장", "wedding_venue"),
    WILDLIFE_PARK("🐾 야생동물 공원", "wildlife_park"),
    WILDLIFE_REFUGE("🐾 야생동물 보호구역", "wildlife_refuge"),
    ZOO("🦁 동물원", "zoo"),

    // 시설
    PUBLIC_BATH("🛁 대중 목욕탕", "public_bath"),
    PUBLIC_BATHROOM("🚻 공중 화장실", "public_bathroom"),
    STABLE("🐴 마구간", "stable"),

    // 금융
    ACCOUNTING("💰 회계사무소", "accounting"),
    ATM("💳 ATM", "atm"),
    BANK("🏦 은행", "bank"),

    // 식음료
    ACAI_SHOP("🍽️ 아사이 전문점", "acai_shop"),
    AFGHANI_RESTAURANT("🍽️ 아프가니 요리점", "afghani_restaurant"),
    AFRICAN_RESTAURANT("🍽️ 아프리카 요리점", "african_restaurant"),
    AMERICAN_RESTAURANT("🍽️ 미국 요리점", "american_restaurant"),
    ASIAN_RESTAURANT("🍽️ 아시아 요리점", "asian_restaurant"),
    BAGEL_SHOP("🍞 베이글 가게", "bagel_shop"),
    BAKERY("🍞 빵집", "bakery"),
    BAR("🍷 바", "bar"),
    BAR_AND_GRILL("🍽️ 바 & 그릴", "bar_and_grill"),
    BARBECUE_RESTAURANT("🍖 바비큐 음식점", "barbecue_restaurant"),
    BRAZILIAN_RESTAURANT("🍽️ 브라질 요리점", "brazilian_restaurant"),
    BREAKFAST_RESTAURANT("🍽️ 아침 식사 전문점", "breakfast_restaurant"),
    BRUNCH_RESTAURANT("🍽️ 브런치 레스토랑", "brunch_restaurant"),
    BUFFET_RESTAURANT("🍽️ 뷔페 레스토랑", "buffet_restaurant"),
    CAFE("☕️ 카페", "cafe"),
    CAFETERIA("🍽️ 구내식당", "cafeteria"),
    CANDY_STORE("🍬 사탕 가게", "candy_store"),
    CAT_CAFE("🐱 고양이 카페", "cat_cafe"),
    CHINESE_RESTAURANT("🍽️ 중국 요리점", "chinese_restaurant"),
    CHOCOLATE_FACTORY("🍫 초콜릿 공장", "chocolate_factory"),
    CHOCOLATE_SHOP("🍫 초콜릿 가게", "chocolate_shop"),
    COFFEE_SHOP("☕️ 커피숍", "coffee_shop"),
    CONFECTIONERY("🍬 과자점", "confectionery"),
    DELI("🥪 델리", "deli"),
    DESSERT_RESTAURANT("🍰 디저트 레스토랑", "dessert_restaurant"),
    DESSERT_SHOP("🍰 디저트 가게", "dessert_shop"),
    DINER("🍽️ 다이너", "diner"),
    DOG_CAFE("🐶 애견 카페", "dog_cafe"),
    DONUT_SHOP("🍩 도넛 가게", "donut_shop"),
    FAST_FOOD_RESTAURANT("🍔 패스트푸드점", "fast_food_restaurant"),
    FINE_DINING_RESTAURANT("🍽️ 고급 레스토랑", "fine_dining_restaurant"),
    FOOD_COURT("🍽️ 푸드코트", "food_court"),
    FRENCH_RESTAURANT("🍽️ 프랑스 요리점", "french_restaurant"),
    GREEK_RESTAURANT("🍽️ 그리스 요리점", "greek_restaurant"),
    HAMBURGER_RESTAURANT("🍔 햄버거 가게", "hamburger_restaurant"),
    ICE_CREAM_SHOP("🍦 아이스크림 가게", "ice_cream_shop"),
    INDIAN_RESTAURANT("🍽️ 인도 요리점", "indian_restaurant"),
    INDONESIAN_RESTAURANT("🍽️ 인도네시아 요리점", "indonesian_restaurant"),
    ITALIAN_RESTAURANT("🍝 이탈리아 요리점", "italian_restaurant"),
    JAPANESE_RESTAURANT("🍣 일식당", "japanese_restaurant"),
    JUICE_SHOP("🥤 주스 전문점", "juice_shop"),
    KOREAN_RESTAURANT("🍽️ 한식당", "korean_restaurant"),
    LEBANESE_RESTAURANT("🍽️ 레바논 요리점", "lebanese_restaurant"),
    MEAL_DELIVERY("🍽️ 음식 배달", "meal_delivery"),
    MEAL_TAKEAWAY("🍽️ 테이크아웃 음식", "meal_takeaway"),
    MEDITERRANEAN_RESTAURANT("🍽️ 지중해 요리점", "mediterranean_restaurant"),
    MEXICAN_RESTAURANT("🍽️ 멕시코 요리점", "mexican_restaurant"),
    MIDDLE_EASTERN_RESTAURANT("🍽️ 중동 요리점", "middle_eastern_restaurant"),
    PIZZA_RESTAURANT("🍕 피자 가게", "pizza_restaurant"),
    PUB("🍺 펍", "pub"),
    RAMEN_RESTAURANT("🍜 라멘 전문점", "ramen_restaurant"),
    RESTAURANT("🍽️ 식당", "restaurant"),
    SANDWICH_SHOP("🥪 샌드위치 가게", "sandwich_shop"),
    SEAFOOD_RESTAURANT("🍣 해산물 요리점", "seafood_restaurant"),
    SPANISH_RESTAURANT("🍽️ 스페인 요리점", "spanish_restaurant"),
    STEAK_HOUSE("🥩 스테이크 하우스", "steak_house"),
    SUSHI_RESTAURANT("🍣 스시집", "sushi_restaurant"),
    TEA_HOUSE("🍵 찻집", "tea_house"),
    THAI_RESTAURANT("🍽️ 태국 요리점", "thai_restaurant"),
    TURKISH_RESTAURANT("🍽️ 터키 요리점", "turkish_restaurant"),
    VEGAN_RESTAURANT("🥗 비건 레스토랑", "vegan_restaurant"),
    VEGETARIAN_RESTAURANT("🥗 채식 레스토랑", "vegetarian_restaurant"),
    VIETNAMESE_RESTAURANT("🍽️ 베트남 요리점", "vietnamese_restaurant"),
    WINE_BAR("🍷 와인 바", "wine_bar"),

    // 지역
    ADMINISTRATIVE_AREA_LEVEL_1("🗺️ 행정 구역 레벨 1", "administrative_area_level_1"),
    ADMINISTRATIVE_AREA_LEVEL_2("🗺️ 행정 구역 레벨 2", "administrative_area_level_2"),
    COUNTRY("🗺️ 국가", "country"),
    LOCALITY("🏙️ 지역", "locality"),
    POSTAL_CODE("📍 우편번호", "postal_code"),
    SCHOOL_DISTRICT("🏫 학군", "school_district"),

    // 정부 기관
    CITY_HALL("🏢 시청", "city_hall"),
    COURTHOUSE("🏛️ 법원", "courthouse"),
    EMBASSY("🏛️ 대사관", "embassy"),
    FIRE_STATION("🚒 소방서", "fire_station"),
    GOVERNMENT_OFFICE("🏛️ 정부 기관", "government_office"),
    LOCAL_GOVERNMENT_OFFICE("🏢 지방 정부 기관", "local_government_office"),
    NEIGHBORHOOD_POLICE_STATION("🚓 파출소", "neighborhood_police_station"),
    POLICE("🚓 경찰서", "police"),
    POST_OFFICE("🏣 우체국", "post_office"),

    // 건강 및 웰니스
    CHIROPRACTOR("💆 척추 지압사", "chiropractor"),
    DENTAL_CLINIC("🏥 치과 클리닉", "dental_clinic"),
    DENTIST("🏥 치과의원", "dentist"),
    DOCTOR("🏥 의사", "doctor"),
    DRUGSTORE("🏪 드럭스토어", "drugstore"),
    HOSPITAL("🏥 병원", "hospital"),
    MASSAGE("💆 마사지", "massage"),
    MEDICAL_LAB("🏥 의료 검사실", "medical_lab"),
    PHARMACY("💊 약국", "pharmacy"),
    PHYSIOTHERAPIST("💆 물리치료사", "physiotherapist"),
    SAUNA("♨️ 사우나", "sauna"),
    SKIN_CARE_CLINIC("💆 피부 클리닉", "skin_care_clinic"),
    SPA("💆 스파", "spa"),
    TANNING_STUDIO("💆 태닝 스튜디오", "tanning_studio"),
    WELLNESS_CENTER("🧘‍♀️ 웰니스 센터", "wellness_center"),
    YOGA_STUDIO("🧘‍♀️ 요가 스튜디오", "yoga_studio"),

    // 주택
    APARTMENT_BUILDING("🏢 아파트 건물", "apartment_building"),
    APARTMENT_COMPLEX("🏢 아파트 단지", "apartment_complex"),
    CONDOMINIUM_COMPLEX("🏢 콘도 단지", "condominium_complex"),
    HOUSING_COMPLEX("🏘️ 주택 단지", "housing_complex"),

    // 숙박시설
    BED_AND_BREAKFAST("🏡 민박(B&B)", "bed_and_breakfast"),
    BUDGET_JAPANESE_INN("🏨 저렴한 일본 여관", "budget_japanese_inn"),
    CAMPGROUND("🏕️ 야영장", "campground"),
    CAMPING_CABIN("🏕️ 캠핑 캐빈", "camping_cabin"),
    COTTAGE("🏡 코티지", "cottage"),
    EXTENDED_STAY_HOTEL("🏨 장기 체류 호텔", "extended_stay_hotel"),
    FARMSTAY("🏡 농가 숙박", "farmstay"),
    GUEST_HOUSE("🏡 게스트하우스", "guest_house"),
    HOSTEL("🏨 호스텔", "hostel"),
    HOTEL("🏨 호텔", "hotel"),
    INN("🏨 여관", "inn"),
    JAPANESE_INN("🏨 일본식 여관", "japanese_inn"),
    LODGING("🛏️ 숙소", "lodging"),
    MOBILE_HOME_PARK("🏕️ 모바일 홈 파크", "mobile_home_park"),
    MOTEL("🏨 모텔", "motel"),
    PRIVATE_GUEST_ROOM("🛏️ 개인 객실", "private_guest_room"),
    RESORT_HOTEL("🏨 리조트 호텔", "resort_hotel"),
    RV_PARK("🏕️ RV 파크", "rv_park"),

    // 자연 지물
    BEACH("🏖️ 해변", "beach"),

    // 예배 장소
    CHURCH("⛪ 교회", "church"),
    HINDU_TEMPLE("🕌 힌두 사원", "hindu_temple"),
    MOSQUE("🕌 모스크", "mosque"),
    SYNAGOGUE("🕍 유대교 회당", "synagogue"),

    // 서비스
    ASTROLOGER("🔮 점성술사", "astrologer"),
    BARBER_SHOP("💇‍♀️ 이발소", "barber_shop"),
    BEAUTICIAN("💇‍♀️ 미용사", "beautician"),
    BEAUTY_SALON("💇‍♀️ 미용실", "beauty_salon"),
    BODY_ART_SERVICE("🪞 바디 아트 서비스", "body_art_service"),
    CATERING_SERVICE("🍽️ 케이터링 서비스", "catering_service"),
    CEMETERY("🪦 묘지", "cemetery"),
    CHILD_CARE_AGENCY("👶 보육 기관", "child_care_agency"),
    CONSULTANT("💼 컨설턴트", "consultant"),
    COURIER_SERVICE("📦 택배 서비스", "courier_service"),
    ELECTRICIAN("🔧 전기 기사", "electrician"),
    FLORIST("💐 꽃집", "florist"),
    FOOD_DELIVERY("🍽️ 음식 배달", "food_delivery"),
    FOOT_CARE("🧴 발 관리", "foot_care"),
    FUNERAL_HOME("⚰️ 장의사", "funeral_home"),
    HAIR_CARE("💇‍♀️ 헤어 케어", "hair_care"),
    HAIR_SALON("💇‍♀️ 헤어 살롱", "hair_salon"),
    INSURANCE_AGENCY("💰 보험 대리점", "insurance_agency"),
    LAUNDRY("🧺 세탁소", "laundry"),
    LAWYER("⚖️ 변호사", "lawyer"),
    LOCKSMITH("🔑 자물쇠 수리공", "locksmith"),
    MAKEUP_ARTIST("💄 메이크업 아티스트", "makeup_artist"),
    MOVING_COMPANY("📦 이삿짐 센터", "moving_company"),
    NAIL_SALON("💅 네일샵", "nail_salon"),
    PAINTER("🎨 페인터", "painter"),
    PLUMBER("🔧 배관공", "plumber"),
    PSYCHIC("🔮 영매", "psychic"),
    REAL_ESTATE_AGENCY("🏢 부동산 중개업소", "real_estate_agency"),
    ROOFING_CONTRACTOR("🔧 지붕 시공업체", "roofing_contractor"),
    STORAGE("📦 창고", "storage"),
    SUMMER_CAMP_ORGANIZER("🏕️ 여름 캠프 주최자", "summer_camp_organizer"),
    TAILOR("🧵 재단사", "tailor"),
    TELECOMMUNICATIONS_SERVICE_PROVIDER("📞 통신 서비스 제공업체", "telecommunications_service_provider"),
    TOUR_AGENCY("📦 투어 업체", "tour_agency"),
    TOURIST_INFORMATION_CENTER("📍 관광 안내소", "tourist_information_center"),
    TRAVEL_AGENCY("📦 여행사", "travel_agency"),
    VETERINARY_CARE("🐾 동물병원", "veterinary_care"),

    // 쇼핑
    ASIAN_GROCERY_STORE("🛒 아시아 식료품점", "asian_grocery_store"),
    AUTO_PARTS_STORE("🛒 자동차 부품점", "auto_parts_store"),
    BICYCLE_STORE("🛒 자전거 가게", "bicycle_store"),
    BOOK_STORE("📚 서점", "book_store"),
    BUTCHER_SHOP("🥩 정육점", "butcher_shop"),
    CELL_PHONE_STORE("📱 휴대폰 가게", "cell_phone_store"),
    CLOTHING_STORE("👗 의류점", "clothing_store"),
    CONVENIENCE_STORE("🛒 편의점", "convenience_store"),
    DEPARTMENT_STORE("🏬 백화점", "department_store"),
    DISCOUNT_STORE("🏬 할인점", "discount_store"),
    ELECTRONICS_STORE("💻 전자제품 매장", "electronics_store"),
    FOOD_STORE("🛒 식료품점", "food_store"),
    FURNITURE_STORE("🛋️ 가구점", "furniture_store"),
    GIFT_SHOP("🎁 기념품점", "gift_shop"),
    GROCERY_STORE("🛒 식료품점(마트)", "grocery_store"),
    HARDWARE_STORE("🔧 철물점", "hardware_store"),
    HOME_GOODS_STORE("🏠 가정용품점", "home_goods_store"),
    HOME_IMPROVEMENT_STORE("🏠 홈 인프루브먼트 스토어", "home_improvement_store"),
    JEWELRY_STORE("💍 보석상", "jewelry_store"),
    LIQUOR_STORE("🍷 주류 판매점", "liquor_store"),
    MARKET("🛍️ 시장", "market"),
    PET_STORE("🐾 애완동물 가게", "pet_store"),
    SHOE_STORE("👟 신발 가게", "shoe_store"),
    SHOPPING_MALL("🏬 쇼핑몰", "shopping_mall"),
    SPORTING_GOODS_STORE("🏋️ 스포츠 용품점", "sporting_goods_store"),
    STORE("🛒 상점", "store"),
    SUPERMARKET("🛒 슈퍼마켓", "supermarket"),
    WAREHOUSE_STORE("🏬 창고형 매장", "warehouse_store"),
    WHOLESALER("🏬 도매상", "wholesaler"),

    // 스포츠
    ARENA("🏟️ 아레나", "arena"),
    ATHLETIC_FIELD("⚽ 운동장", "athletic_field"),
    FISHING_CHARTER("🎣 낚시 전세", "fishing_charter"),
    FISHING_POND("🎣 낚시터", "fishing_pond"),
    FITNESS_CENTER("🏋️ 피트니스 센터", "fitness_center"),
    GOLF_COURSE("⛳ 골프장", "golf_course"),
    GYM("🏋️ 체육관", "gym"),
    ICE_SKATING_RINK("⛸️ 아이스 스케이트장", "ice_skating_rink"),
    PLAYGROUND("🛝 놀이터", "playground"),
    SKI_RESORT("⛷️ 스키 리조트", "ski_resort"),
    SPORTS_ACTIVITY_LOCATION("🏋️ 스포츠 활동 장소", "sports_activity_location"),
    SPORTS_CLUB("🏋️ 스포츠 클럽", "sports_club"),
    SPORTS_COACHING("🏋️ 스포츠 코칭", "sports_coaching"),
    SPORTS_COMPLEX("🏋️ 스포츠 콤플렉스", "sports_complex"),
    STADIUM("🏟️ 경기장", "stadium"),
    SWIMMING_POOL("🏊‍♂️ 수영장", "swimming_pool"),

    // 교통
    AIRPORT("✈️ 공항", "airport"),
    AIRSTRIP("✈️ 활주로", "airstrip"),
    BUS_STATION("🚌 버스 터미널", "bus_station"),
    BUS_STOP("🚌 버스 정류장", "bus_stop"),
    FERRY_TERMINAL("⛴️ 페리 터미널", "ferry_terminal"),
    HELIPORT("🚁 헬리포트", "heliport"),
    INTERNATIONAL_AIRPORT("✈️ 국제공항", "international_airport"),
    LIGHT_RAIL_STATION("🚉 경전철 역", "light_rail_station"),
    PARK_AND_RIDE("🅿️ 파크 앤 라이드", "park_and_ride"),
    SUBWAY_STATION("🚉 지하철역", "subway_station"),
    TAXI_STAND("🚕 택시 승강장", "taxi_stand"),
    TRAIN_STATION("🚉 기차역", "train_station"),
    TRANSIT_DEPOT("🚉 환승 기지", "transit_depot"),
    TRANSIT_STATION("🚉 환승역", "transit_station"),
    TRUCK_STOP("🚚 트럭 휴게소", "truck_stop"),

    // 표 B - 추가 장소 유형 값
    ADMINISTRATIVE_AREA_LEVEL_3("🌐 행정 구역 레벨 3", "administrative_area_level_3"),
    ADMINISTRATIVE_AREA_LEVEL_4("🌐 행정 구역 레벨 4", "administrative_area_level_4"),
    ADMINISTRATIVE_AREA_LEVEL_5("🌐 행정 구역 레벨 5", "administrative_area_level_5"),
    ADMINISTRATIVE_AREA_LEVEL_6("🌐 행정 구역 레벨 6", "administrative_area_level_6"),
    ADMINISTRATIVE_AREA_LEVEL_7("🌐 행정 구역 레벨 7", "administrative_area_level_7"),
    ARCHIPELAGO("🗾 군도", "archipelago"),
    COLLOQUIAL_AREA("📌 구어적 지역명", "colloquial_area"),
    CONTINENT("🌐 대륙", "continent"),
    ESTABLISHMENT("🏢 시설/기관", "establishment"),
    FINANCE("💰 금융", "finance"),
    FOOD("🍽️ 음식", "food"),
    GENERAL_CONTRACTOR("🏢 종합 건설업체", "general_contractor"),
    GEOCODE("🌐 지오코드", "geocode"),
    HEALTH("🏥 건강", "health"),
    INTERSECTION("🛣️ 교차로", "intersection"),
    LANDMARK("📍 랜드마크", "landmark"),
    NATURAL_FEATURE("🏞️ 자연 지물", "natural_feature"),
    NEIGHBORHOOD("🏘️ 동네", "neighborhood"),
    PLACE_OF_WORSHIP("⛪ 예배 장소", "place_of_worship"),
    PLUS_CODE("🌐 플러스 코드", "plus_code"),
    POINT_OF_INTEREST("📍 관심 지점(POI)", "point_of_interest"),
    POLITICAL("🏛️ 행정 구역(정치적)", "political"),
    POSTAL_CODE_PREFIX("📍 우편번호 접두사", "postal_code_prefix"),
    POSTAL_CODE_SUFFIX("📍 우편번호 접미사", "postal_code_suffix"),
    POSTAL_TOWN("🏙️ 우편 구역(타운)", "postal_town"),
    PREMISE("🏢 건물/부지", "premise"),
    ROUTE("🛣️ 도로/경로", "route"),
    STREET_ADDRESS("🏠 도로명 주소", "street_address"),
    SUBLOCALITY("🏘️ 하위 지역", "sublocality"),
    SUBLOCALITY_LEVEL_1("🏘️ 하위 지역 레벨 1", "sublocality_level_1"),
    SUBLOCALITY_LEVEL_2("🏘️ 하위 지역 레벨 2", "sublocality_level_2"),
    SUBLOCALITY_LEVEL_3("🏘️ 하위 지역 레벨 3", "sublocality_level_3"),
    SUBLOCALITY_LEVEL_4("🏘️ 하위 지역 레벨 4", "sublocality_level_4"),
    SUBLOCALITY_LEVEL_5("🏘️ 하위 지역 레벨 5", "sublocality_level_5"),
    SUBPREMISE("🏢 하위 건물/부지", "subpremise"),
    TOWN_SQUARE("🏞️ 광장(타운 스퀘어)", "town_square"),

    NONE("🚫 없음", "none");

    private final String koreanCategoryName;
    private final String englishCategoryName;

    GoogleMapCategory(final String koreanCategoryName, final String englishCategoryName) {
        this.koreanCategoryName = koreanCategoryName;
        this.englishCategoryName = englishCategoryName;
    }

    public static String parseCategoryName(String categoryName) {
        GoogleMapCategory category = ofEnglishCategoryName(categoryName);
        if (category == NONE) {
            return categoryName;
        }
        return category.koreanCategoryName;
    }

    private static GoogleMapCategory ofEnglishCategoryName(String englishCategoryName) {
        return Arrays.stream(GoogleMapCategory.values())
                .filter(category -> category.englishCategoryName.equals(englishCategoryName))
                .findFirst()
                .orElse(NONE);
    }
}
