package turip.place.domain;

import java.util.Arrays;
import java.util.Map;
import java.util.stream.Collectors;
import lombok.Getter;

@Getter
public enum KakaoMapCategory {
    FURNITURE_STORE("🛋️ 가구판매"),
    STATIONERY("📝 문구,사무용품"),
    DESIGN_STATIONERY("📝 디자인문구"),
    PET("🐾 반려동물"),
    SHINSEGAE_DEPARTMENT_STORE("🏬 신세계백화점"),
    HYUNDAI_DEPARTMENT_STORE("🏬 현대백화점"),
    SHOPPING_ARCADE("🏬 상가,아케이드"),
    LOTTE_OUTLET("🏬 롯데아울렛"),
    HOUSEHOLD_GOODS_STORE("🏠 생활용품점"),
    INTERIOR_DECORATION("🏠 인테리어장식판매"),
    KITCHENWARE("🍳 주방용품"),
    SUPERMARKET("🛒 슈퍼마켓"),
    MARKET("🛍️ 시장"),
    FOOD_SALE("🛒 식품판매"),
    FRUIT_VEGETABLE_STORE("🥕 과일,채소가게"),
    SEAFOOD_SALE("🐟 수산물판매"),
    BUTCHER_SHOP("🥩 정육점"),
    TOYS_R_US("🧸 토이저러스"),
    FASHION("👗 패션"),
    CLOTHING_STORE("👗 의류판매"),
    IMPORTED_CLOTHING("👗 수입의류"),
    ZARA("👗 ZARA"),
    FASHION_ACCESSORIES("👜 패션잡화점"),
    SHOES("👟 구두,신발"),
    GLASSES_LENSES("👓 안경,렌즈"),
    PHONE_ACCESSORIES("📱 폰액세서리"),
    AIRPORT("✈️ 공항"),
    CRUISE_SHIP_DOCK("⛴️ 유람선선착장"),
    PASSENGER_FERRY_TERMINAL("⛴️ 여객선터미널"),
    HARBOR("⛵ 항구,포구"),
    KTX_SRT_STATION("🚉 KTX,SRT정차역"),
    BRIDGE("🌉 교량,다리"),
    INTERSECTION("🛣️ 교차로"),
    ENTRANCE_EXIT("🚪 입출구"),
    HIGHWAY_REST_AREA("🚗 고속도로휴게소"),
    BOOKSTORE("📚 서점"),
    INDEPENDENT_BOOKSTORE("📚 독립서점"),
    CULTURAL_FACILITIES("🏛️ 문화시설"),
    ART_MUSEUM("🖼️ 미술관"),
    MUSEUM("🏛️ 박물관"),
    AQUARIUM("🏞️ 아쿠아리움"),
    EXHIBITION_HALL("🏢 전시관"),
    ART_CRAFT("🎨 미술,공예"),
    GALLERY("🖼️ 화랑"),
    PHOTO_STUDIO("📷 사진관,포토스튜디오"),
    PHOTOISM_BOX("📷 포토이즘박스"),
    BUDDHIST_TEMPLE("🏯 절,사찰"),
    CATHOLIC_CHURCH("⛪ 성당"),
    PLACE_NAME("📍 지명"),
    LIQUOR_WHOLESALE("🍷 주류도매,주류유통"),
    ENERGY_COMPANY("💡 에너지기업"),
    SPACE_RENTAL("🎤 공간대여"),
    FARM_RANCH("🌾 농장,목장"),
    WATER_SPORTS("🏊‍♂️ 수상스포츠"),
    SPORTS_FACILITIES("🏋️ 스포츠시설"),
    SHOOTING_ARCHERY("🏹 사격,궁도"),
    PRO_BASEBALL_STADIUM("🏟️ 프로야구장"),
    BICYCLE("🚴 자전거,싸이클"),
    PARK("🏞️ 공원"),
    URBAN_NEIGHBORHOOD_PARK("🏞️ 도시근린공원"),
    PARK_FACILITIES("🏞️ 공원시설물"),
    TOURIST_ATTRACTION("📍 관광,명소"),
    TOURIST_FARM("🌾 관광농원"),
    TOURIST_COMPLEX("📍 관광단지"),
    TOURIST_INFORMATION_CENTER("📍 관광안내소"),
    PLAZA("🏞️ 광장"),
    PROVINCIAL_PARK("🏞️ 도립공원"),
    DULLE_GIL("🥾 둘레길"),
    JEJU_OLLE_GIL("🥾 제주올레길"),
    HAEPARANG_GIL("🥾 해파랑길"),
    DRIVE_COURSE("🚗 드라이브코스"),
    CULTURAL_HERITAGE("🏛️ 문화유적"),
    TOMB("🪦 릉,묘,총"),
    SHRINE_ALTAR("🏛️ 사당,제단"),
    HISTORIC_SITE("🏛️ 유적지"),
    HYANGGYO_SEODANG("🏛️ 향교,서당"),
    FOLK_VILLAGE("📍 민속촌"),
    ROCK("🏞️ 바위"),
    MOUNTAIN("🏞️ 산"),
    MOUNTAIN_PEAK("🏞️ 산봉우리"),
    ISLAND("🗾 섬"),
    INLAND_ISLAND("🗾 섬(내륙)"),
    ARBORETUM_BOTANICAL_GARDEN("🏞️ 수목원,식물원"),
    FOREST("🏞️ 숲"),
    OREUM("🏞️ 오름"),
    RECREATIONAL_FOREST("🏞️ 자연휴양림"),
    OBSERVATORY("🔭 전망대"),
    CABLE_CAR("🚠 케이블카"),
    THEME_STREET("🛣️ 테마거리"),
    THEME_PARK("🎡 테마파크"),
    WATERFALL("🏞️ 폭포"),
    BEACH("🏖️ 해수욕장,해변"),
    LAKE("🏞️ 호수"),
    SOUVENIR_SHOP("🎁 기념품판매"),
    LODGING("🛏️ 숙박"),
    GUEST_HOUSE("🏡 게스트하우스"),
    MOTEL("🏨 여관,모텔"),
    SONO_HOTELS_RESORTS("🏨 소노호텔앤리조트"),
    HANWHA_RESORT("🏨 한화리조트"),
    PENSION("🏡 펜션"),
    HANOK_STAY("🏯 한옥숙소"),
    HOTEL("🏨 호텔"),
    RAMADA_HOTEL("🏨 라마다호텔"),
    LOTTE_HOTEL("🏨 롯데호텔"),
    SHILLA_HOTEL("🏨 신라호텔"),
    SNACK("🥨 간식"),
    DAKGANGJEONG("🍗 닭강정"),
    DONUT("🍩 도넛"),
    RICE_CAKE_KOREAN_SWEETS("🍡 떡,한과"),
    BASKIN_ROBBINS("🍦 배스킨라빈스"),
    BAKERY("🍞 제과,베이커리"),
    PARIS_BAGUETTE("🍞 파리바게뜨"),
    BUNSIK("🍢 분식"),
    TTEOKBOKKI("🍢 떡볶이"),
    WINE_BAR("🍷 와인바"),
    JAPANESE_BAR("🍺 일본식주점"),
    HOF_PUB("🍺 호프,요리주점"),
    ASIAN_FOOD("🍽️ 아시아음식"),
    VIETNAMESE_FOOD("🍽️ 베트남음식"),
    WESTERN_FOOD("🍽️ 양식"),
    MEXICAN_BRAZILIAN("🍽️ 멕시칸,브라질"),
    PIZZA("🍕 피자"),
    HAMBURGER("🍔 햄버거"),
    JAPANESE_FOOD("🍣 일식"),
    DONKATSU_UDON("🍣 돈까스,우동"),
    JAPANESE_RAMEN("🍜 일본식라면"),
    JAPANESE_RESTAURANT("🍣 일식집"),
    TUNA_SASHIMI("🍣 참치회"),
    SUSHI_ROLL("🍣 초밥,롤"),
    CHINESE_FOOD("🥡 중국요리"),
    CHICKEN("🍗 치킨"),
    CAFE("☕ 카페"),
    TRADITIONAL_TEAHOUSE("🍵 전통찻집"),
    COFFEE_SHOP("☕ 커피전문점"),
    BLUE_BOTTLE("☕ 블루보틀"),
    STARBUCKS("☕ 스타벅스"),
    THEME_CAFE("☕ 테마카페"),
    DESSERT_CAFE("🍰 디저트카페"),
    KNOTTED_DONUT("🍩 노티드"),
    BOOK_CAFE("📚 북카페"),
    KOREAN_FOOD("🍚 한식"),
    GAMJATANG("🥘 감자탕"),
    GUKBAP("🥣 국밥"),
    JEONJU_HYUNDAIOK("🥣 전주현대옥"),
    NOODLES("🍜 국수"),
    KALGUKSU("🍜 칼국수"),
    TOFU_RESTAURANT("🍽️ 두부전문점"),
    SUNDAE("🍽️ 순대"),
    OBONGJIP("🍽️ 오봉집"),
    MEAT("🍖 육류,고기"),
    GALBI("🍖 갈비"),
    GOPCHANG_MAKCHANG("🍖 곱창,막창"),
    CHICKEN_DISH("🍗 닭요리"),
    SAMGYEOPSAL("🍖 삼겹살"),
    DUCK("🦆 오리"),
    SEAFOOD_FISH("🐟 해물,생선"),
    CRAB("🦀 게,대게"),
    OYSTER_ABALONE("🦪 굴,전복"),
    ANGLERFISH("🐟 아구"),
    CLAM("🦪 조개"),
    SASHIMI("🍣 회"),
    HAEJANGGUK("🥣 해장국"),
    CLOSED("🚫 폐업"),
    TEMPORARILY_CLOSED("🚫 휴관"),

    NONE("🚫 없음");

    private static final Map<String, KakaoMapCategory> CATEGORY_MAP =
            Arrays.stream(values())
                    .filter(cat -> cat != NONE)
                    .collect(Collectors.toMap(
                            cat -> cat.koreanCategoryName.substring(cat.koreanCategoryName.indexOf(" ") + 1),
                            cat -> cat
                    ));
    private final String koreanCategoryName;

    KakaoMapCategory(final String koreanCategoryName) {
        this.koreanCategoryName = koreanCategoryName;
    }

    public static String parseCategoryName(String categoryName) {
        KakaoMapCategory category = CATEGORY_MAP.get(categoryName);
        if (category == null) {
            return categoryName;
        }
        return category.koreanCategoryName;
    }
}
