spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/turip_dev
    username: turip
    password: turip_pw

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        # 개발 환경에서는 스키마 검증을 완화
        validator:
          apply_to_ddl: false

  sql:
    init:
      mode: never

  flyway:
    enabled: true
    locations: classpath:db/migration, classpath:db/migration,classpath:db/dev
    baseline-on-migrate: true
    validate-on-migrate: true
    encoding: UTF-8

management:
  endpoint:
    health:
      show-details: always

# CSV Import 설정
csv:
  import:
    password: ${CSV_IMPORT_PASSWORD:dev_password_123}
  links:
    collection-url: ${CSV_LINKS_COLLECTION_URL}

logging:
  level:
    root: INFO
