spring:
  profiles:
    active: local

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    defer-datasource-initialization: false

region:
  category:
    domestic:
      etc:
        image-url: ${DOMESTIC_ETC_IMAGE_URL}
    overseas:
      etc:
        image-url: ${OVERSEAS_ETC_IMAGE_URL}

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    health:
      show-details: always

server:
  tomcat:
    mbeanregistry:
      enabled: true
