name: dev CI/CD with Docker and Nginx

on:
  push:
    branches: [ develop ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ develop ]
    paths:
      - 'backend/**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Prepare OpenTelemetry agent
        run: |
          mkdir -p otel
          curl -L -o otel/opentelemetry-javaagent.jar \
          https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v2.10.0/opentelemetry-javaagent.jar

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/arm64
          push: true
          tags: |
            teamturip/turip-backend:${{ github.sha }}
            teamturip/turip-backend:latest

  deploy:
    needs: build_and_test
    runs-on: [ self-hosted, turip-server-dev ]
    environment: development
    if: github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Grant execute permission for deploy script
        run: chmod +x /home/ubuntu/deploy/deploy.sh

      - name: Deploy to EC2
        working-directory: /home/ubuntu/deploy
        env:
          DOCKER_IMAGE_NAME: teamturip/turip-backend:latest
          CSV_LINKS_COLLECTION_URL: ${{ secrets.CSV_LINKS_COLLECTION_URL }}
          OVERSEAS_ETC_IMAGE_URL: ${{ secrets.OVERSEAS_ETC_IMAGE_URL }}
          DOMESTIC_ETC_IMAGE_URL: ${{ secrets.DOMESTIC_ETC_IMAGE_URL }}
          OTEL_EXPORTER_OTLP_ENDPOINT: ${{ secrets.OTEL_EXPORTER_OTLP_ENDPOINT }}
          MYSQL_URL: ${{ secrets.MYSQL_URL }}
          MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          FLYWAY_USERNAME: ${{ secrets.FLYWAY_USERNAME }}
          FLYWAY_PASSWORD: ${{ secrets.FLYWAY_PASSWORD }}
          CSV_IMPORT_PASSWORD: ${{ secrets.CSV_IMPORT_PASSWORD }}
        run: ./deploy.sh
