name: dev CI/CD with Docker and Nginx

on:
  push:
    branches: [ develop ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ develop ]
    paths:
      - 'backend/**'

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Download OpenTelemetry Agent #dockerfile에 OpenTelemetry에 대한 jar 파일 받으라고 되어있으니 이 부분 없어도 되는건가?
        run: curl -L -o opentelemetry-javaagent.jar https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6 #여기서 dockerfile에 적힌대로 애플리케이션 이미지 빌드하고 도커 허브에 푸시
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: teamturip/turip-backend:${{ github.sha }}

  deploy:
    needs: build_and_test
    runs-on: [ self-hosted, turip-server-dev ]
    environment: development
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Grant execute permission for deploy script
        run: chmod +x backend/deploy.sh

      - name: Deploy to EC2
        working-directory: backend
        env:
          DOCKER_IMAGE_NAME: teamturip/turip-backend:${{ github.sha }}
        run: ./deploy.sh
